CREATE TABLE patients (id BIGINT AUTO_INCREMENT NOT NULL, address VARCHAR(255), city VARCHAR(255), cover_image_url VARCHAR(255), created_by VARCHAR(255), created_date DATETIME, email_address VARCHAR(255), first_name VARCHAR(255), gender VARCHAR(255), last_name VARCHAR(255), name VARCHAR(255), nationality VARCHAR(255), occupation VARCHAR(255), primary_phone VARCHAR(255), social_security_number VARCHAR(255), status VARCHAR(255), updated_date DATETIME, updated_by VARCHAR(255), PRIMARY KEY (id))
CREATE TABLE patient_condition (id BIGINT AUTO_INCREMENT NOT NULL, description VARCHAR(255), diagnosis_id VARCHAR(255), patient_id BIGINT, PRIMARY KEY (id))
CREATE TABLE diagnoses (diagnosis_code VARCHAR(255) NOT NULL, long_description VARCHAR(2048), short_description VARCHAR(255), PRIMARY KEY (diagnosis_code))
CREATE TABLE patient_needs (ID BIGINT AUTO_INCREMENT NOT NULL, code VARCHAR(255), description VARCHAR(255), need_type INTEGER, value INTEGER, condition_id BIGINT, PRIMARY KEY (ID))
CREATE TABLE campaigns (id BIGINT AUTO_INCREMENT NOT NULL, amount_donated DECIMAL(38), patient_condition VARCHAR(255), cover_image_url VARCHAR(255), created_by VARCHAR(255), created_date DATETIME, description VARCHAR(255), diagnosis VARCHAR(255), email_address VARCHAR(255), no_of_donors INTEGER, patient_name VARCHAR(255), status VARCHAR(255), target DECIMAL(38), title VARCHAR(255), total_endorsed INTEGER, total_following INTEGER, updated_date DATETIME, updated_by VARCHAR(255), PRIMARY KEY (id))
CREATE TABLE media (id BIGINT AUTO_INCREMENT NOT NULL, filename VARCHAR(255), mimetype VARCHAR(255), path VARCHAR(255), campaign_id BIGINT, PRIMARY KEY (id))
CREATE TABLE campaign_donors (CAMPAIGNID INTEGER NOT NULL, DONORID INTEGER NOT NULL, amount DECIMAL(38), payment_date DATETIME, payment_type INTEGER, campaign_id BIGINT, donor_id BIGINT, PRIMARY KEY (CAMPAIGNID, DONORID))
CREATE TABLE campaign_endorses (DOCTORID INTEGER NOT NULL, CAMPAIGNID INTEGER NOT NULL, campaign_id BIGINT, doctor_id BIGINT, PRIMARY KEY (DOCTORID, CAMPAIGNID))
CREATE TABLE campaign_followers (DOCTORID INTEGER NOT NULL, CAMPAIGNID INTEGER NOT NULL, campaign_id BIGINT, follower_id BIGINT, PRIMARY KEY (DOCTORID, CAMPAIGNID))
CREATE TABLE users (id BIGINT AUTO_INCREMENT NOT NULL, first_name VARCHAR(255), FULLNAME VARCHAR(255), last_name VARCHAR(255), PRIMARY KEY (id))
ALTER TABLE diagnoses ADD CONSTRAINT UNQ_diagnoses_0 UNIQUE (diagnosis_code)
ALTER TABLE patient_condition ADD CONSTRAINT FK_patient_condition_patient_id FOREIGN KEY (patient_id) REFERENCES patients (id)
ALTER TABLE patient_condition ADD CONSTRAINT FK_patient_condition_diagnosis_id FOREIGN KEY (diagnosis_id) REFERENCES diagnoses (diagnosis_code)
ALTER TABLE patient_needs ADD CONSTRAINT FK_patient_needs_condition_id FOREIGN KEY (condition_id) REFERENCES patient_condition (id)
ALTER TABLE media ADD CONSTRAINT FK_media_campaign_id FOREIGN KEY (campaign_id) REFERENCES campaigns (id)
ALTER TABLE campaign_donors ADD CONSTRAINT FK_campaign_donors_campaign_id FOREIGN KEY (campaign_id) REFERENCES campaigns (id)
ALTER TABLE campaign_donors ADD CONSTRAINT FK_campaign_donors_donor_id FOREIGN KEY (donor_id) REFERENCES users (id)
ALTER TABLE campaign_endorses ADD CONSTRAINT FK_campaign_endorses_doctor_id FOREIGN KEY (doctor_id) REFERENCES users (id)
ALTER TABLE campaign_endorses ADD CONSTRAINT FK_campaign_endorses_campaign_id FOREIGN KEY (campaign_id) REFERENCES campaigns (id)
ALTER TABLE campaign_followers ADD CONSTRAINT FK_campaign_followers_campaign_id FOREIGN KEY (campaign_id) REFERENCES campaigns (id)
ALTER TABLE campaign_followers ADD CONSTRAINT FK_campaign_followers_follower_id FOREIGN KEY (follower_id) REFERENCES users (id)
